### PR TITLE
Suggested short-cut for syncing notebooks from pelican to binder repo

### PR DESCRIPTION
**Pull request by fangohr**

### CODE REVIEW

**Comment by kirienko** [comment]
Shouldn't we add `nbdata` files as well?

**Comment by kirienko** [comment]
Sorry, I don't understand how all this machinery works :shrug: 
Could you give some explanation somewhere, or maybe we have some Binder-related tutorial?

**Comment by fangohr** [comment]
@RobertRosca , I think these changes are not necessary anymore as you do the synchronisation automatically? 

If so, could you add the relevant information to our info.md file that summarises the workflow, please? We can then close the PR without merging it as the functionality is not required (and it is not pretty anyway).

**Comment by fangohr** [comment]
We discussed yesterday there is no harm in merging this; just in case it is needed at some point.

**Pull request merged**
