### PR TITLE
Force py.test >=4.6 to work around CI bug with python 3.6 and 3.7.

### PR DESCRIPTION
**Pull request by fangohr**
More of a diagnostic experiment than a fix

### CODE REVIEW

**Comment by RobertRosca** [comment]
Issue seems to be that Travis includes pytest version 4.3.1 by default for python 3.7 and 3.6, but it uses version 5.2.1 for python 3.8.

This isn't mentioned in the travis documentation anywhere as far as I can see, had to mabe a ci that ran `pip list` to see what was installed by default, the full list is:

```
Python 3.7.1

Package          Version   
---------------- ----------
atomicwrites     1.2.1     
attrs            18.2.0    
certifi          2018.11.29
mock             2.0.0     
more-itertools   4.3.0     
nose             1.3.7     
numpy            1.15.4    
pbr              5.1.1     
pip              19.0.3    
pipenv           2018.11.26
pluggy           0.8.0     
py               1.7.0     
pytest           4.3.1     
setuptools       40.8.0    
six              1.11.0    
virtualenv       16.1.0    
virtualenv-clone 0.4.0     
wheel            0.33.1    
```

Updating everything before the package is installed seems like a sensible way to get around outdated versions of these packages being included.

**Comment by fangohr** [comment]
Thanks, Robert. I prefer the fix in my second commit https://github.com/fangohr/coronavirus-2020/pull/60/commits/4b3fb883638399c9a26811a1770ee44ade1eccfd which forces only a newer version of py.test which also seems to fix the matter.

[Upgrade all libraries to the latest version may attract problems due to bugs in new features etc.]

Can you review this version?

**Comment by fangohr** [comment]
For reference: this is the problem we are trying to fix:

https://travis-ci.org/github/fangohr/coronavirus-2020/jobs/698133795#L374

**Comment by RobertRosca** [comment]
Oh yeah, I was about to reply to that before and saw your PR so I commented here instead :stuck_out_tongue: 

Hmm, like with most of my reviews, this is a good solution and LGTM, but I do have some slightly pedantic comments that don't really affect how well the code works.

Setting the version limit for pytest looks like we need that version for the tests to pass, which we don't as the compatibility problem is with `pytest-cov` used to create/upload the code coverage stuff. Since this only gets used in the CI job and not in local testing forcing that minimum version everywhere isn't necessary. I think that adding a line to the `.travis.yml` would fix this:

```
install:
  - pip install -U pytest
  - make dev-install
```

This'll force the pytest update during the CI tests, and avoids adding the version requirement to the package itself.

**Comment by fangohr** [comment]
Nice idea, Robert - you are right. Changed as you suggested. Thanks!

**Pull request merged**
