### PR TITLE
List improvements

### PR DESCRIPTION
**Pull request by RobertRosca**
Changes:
- Changed the pelican plumage theme:
  - imports newer jquery version, moved import to top
  - imports datatables js and css from cdn
  - added js scripts to enable datatables
  - added (dodgy) script to tag all tables with the same ID so that datatables formats them - no easy way in pelican to tag a specific markdown table with a specific ID far as I can find :cry: 
- Changed generate countries:
  - made pandas never use scientific notation otherwise country cases show up as 1.129e4 or something
  - `create_md_index_list` now takes in the title; a table where the index should be a region name, and the two columns should be `Total cases` and `Total deaths`; and the dict of links. Index elements are then replaced with the dict values where they exist, this way regions with no notebook still show up in the table but just have no link
- Added tabulate to requirements

The way index tables are generated is a bit weird, especially for Germany, but fixing it would require changing the coronavirus.py code and I wanted to avoid that as Thomas is working on it.

Also, the generated Germany markdown file is missing a lot of the states, think that was the same issue you mentioned to me before Hans, I didn't fix it  since I forgot what you said the problem (and solution) was.

### CODE REVIEW

**Comment by RobertRosca** [comment]
If everything worked correctly the index and Germany pages should have a searchable and sortable table now:

image

**Comment by fangohr** [comment]
Very nice! 

Observations:

- `tabulate` is a new requirement (should go to setup.py and tools/requirements-for-binder.txt).

- Something goes wrong in the calculation of the cases and  deaths for the world. For example Hamburg: 
   ```
   Germany | 2252429 | 37805
  ```
  where as actual numbers are 
  ```
  134753 | 3804
  ```
   Is it possible you have summed over all the entries in series, and the series is already the cumulative count?

Going beyond the basics and this merge request:

Can we define the beginning order of entries in the table? At the moment it is alphabetic, I think. Might be nice to have it in order of decreasing cases or deaths.


Very nice UX element.

**Comment by RobertRosca** [comment]
- [x] tables are sorted by the first column (case number) by default now
 - [x] added tabulate to setup.py
 - [x] added comma separator for case and death numbers in the table to make it more readable
 - [x] fixed the world death counts (assumed each date was new cases so I summed it, turns out they're cumulative like you said so now is takes the final column instead)

**Comment by fangohr** [comment]
Very nice. 

One more question: for the list of regions/countries, one can select to see 10, 50 or 100 entries. 

Can we add an option to show 500 entries? This would make it possible to quickly scroll through the whole list to see what is available (if alphabetically sorted, for example).

**Pull request merged**
