### PR TITLE
change overview function: by default show only the last 5 weeks

### PR DESCRIPTION
**Pull request by kirienko**
I tried different variants, but the final result turned out to be reducible to _two lines of code_:
* a new parameter `weeks = 5` was added to the `overview` function;
* a reduction of `c` and `d` series:
```c, d = c[- weeks * 7:], d[- weeks * 7:]```

This interface allows see the whole time range simply by setting `weeks = 0`. 

Also in this PR (as a byproduct): 
* type annotations were added here and there (not everywhere, but only where I needed it);
* some PEP8 fixes

We [may] need to add to this PR:
- [ ] documentation of this `weeks` feature (where?)
- [ ] maybe add another parameter like `start_at = '2020-04-04'` — to start with an arbitrary day. Not sure we really need that, but it may enrich usability. The possible argument against it is overcomplicaton of the function
- [ ] we may decide to add this feature not to all graphs, but only to several of them.

Solves #51

### CODE REVIEW

**Comment by RobertRosca** [comment]
Just tested it locally and everything works well, so LGTM :+1:

Since you're going on holiday I'll wait a bit and see if you merge it yourself soon, if not then I'll do it tomorrow. Enjoy your break :grin:  

Also inspired me to make an issue #81 to make a staging repository so that we can automatically test the website generation on a PR.

**Comment by RobertRosca** [comment]
Merged maser into your branch so that it will run the new staging website generation ci

**Comment by fangohr** [comment]
Hi - thanks for this. I think we must show the all time overview as well. Maybe first the overview for the whole duration of the pandemic, and then the new last 5 week update as a second figure in a new cell below.

**Comment by kirienko** [comment]
I think we it can me merged now.

**Comment by kirienko** [comment]
Thanks for the detailed review and discussion!

**Pull request merged**
