### PR TITLE
Reorganize package

### PR DESCRIPTION
**Pull request by tmichela**
My changes start to get much larger than expected. So I'll try to split the work.
This only package the project and reorganize the files (code source, tests, notebooks)

### CODE REVIEW

**Comment by fangohr** [comment]
Thank you - looks good. (Seems sensible to proceed in small steps.)

Observations:

- CI fails (probably just a matter of the test-pycodestyle target not working (missing dependency)?
- the notebook in `tools/generate-countries.html` is important as it creates the updates plots. This doesn't execute at the moment (stops at `clear_cache`) not being available.

The testing in the Dockerfile can be useful to debug what's going on on Travis, or be able to run the code in a container in a system you don't want to configure, but I agree that it makes the travis CI less clear; so I am happy for that to be removed.

**Comment by tmichela** [comment]
Good point on Docker, I'll put back the makefile options

**Comment by tmichela** [comment]
Build still fails, but now we can see it's due to the codestyle check (should the style test be part of ci?):

```bash
python3 -m pycodestyle .
./setup.py:65:1: E124 closing bracket does not match visual indentation
./coronavirus/coronavirus.py:19:1: E402 module level import not at top of file
[...]
./coronavirus/coronavirus.py:357:80: E501 line too long (112 > 79 characters)
./tests/test_corona.py:136:1: W391 blank line at end of file
Makefile:13: recipe for target 'test-pycodestyle' failed
make: *** [test-pycodestyle] Error 1
The command "make test-all" exited with 2.
Done. Your build exited with 1.
```

**Comment by fangohr** [comment]
> Build still fails, but now we can see it's due to the codestyle check (should the style test be part of ci?):
> 
> ```shell
> python3 -m pycodestyle .
> ./setup.py:65:1: E124 closing bracket does not match visual indentation
> ./coronavirus/coronavirus.py:19:1: E402 module level import not at top of file
> [...]
> ./coronavirus/coronavirus.py:357:80: E501 line too long (112 > 79 characters)
> ./tests/test_corona.py:136:1: W391 blank line at end of file
> Makefile:13: recipe for target 'test-pycodestyle' failed
> make: *** [test-pycodestyle] Error 1
> The command "make test-all" exited with 2.
> Done. Your build exited with 1.
> ```

The codestyle test never passed. I only put it in as wishful thinking - at some point I hope we can make it pass :). Please comment this out for now.

**Comment by fangohr** [comment]
Great, thank you. 

There is a little more work to be done in generate-countries.html. I am happy to do this, but could please pull from the latest master into this branch (so that I get Robert's parallel version of generate-countries.ipynb and do my modifications on this).

[Context: When you go to one of the generated webpages (such as https://fangohr.github.io/coronavirus/html/Afghanistan.html), there is a link where you can execute the notebook on Binder. We need to have the rigth files in the right place for that.]

**Comment by tmichela** [comment]
@fangohr I started to fix that here: https://github.com/fangohr/coronavirus-2020/tree/make_generation_work

Not working so far, I probably overlook something, you might have an idea of what I'm doing wrong:

```bash
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
overview("Afghanistan");
------------------

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-0cceea519632> in <module>
----> 1 overview("Afghanistan");

~/anaconda3/lib/python3.7/site-packages/coronavirus/coronavirus.py in overview(country, region, subregion, savefig)
    728 
    729     if not subregion and not region: # i.e. not a region of Germany
--> 730         axes_compare, res_c, res_d = make_compare_plot(country)
    731         return_axes = np.concatenate([axes, axes_compare])
    732 

~/anaconda3/lib/python3.7/site-packages/coronavirus/coronavirus.py in make_compare_plot(main_country, compare_with, v0c, v0d)
    542     rolling = 7
    543     df_c, df_d = get_compare_data([main_country] + compare_with, rolling=rolling)
--> 544     res_c = align_sets_at(v0c, df_c)
    545     res_d = align_sets_at(v0d, df_d)
    546     fig, axes = plt.subplots(2, 1, figsize=(10, 6))

~/anaconda3/lib/python3.7/site-packages/coronavirus/coronavirus.py in align_sets_at(v0, df)
    477         series = day0atleast(v0, df[col])
    478         series.name = col
--> 479         res = pd.merge(res, series, how='outer', left_index=True, right_index=True)
    480 
    481     return res

~/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/merge.py in merge(left, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator, validate)
     59                          right_index=right_index, sort=sort, suffixes=suffixes,
     60                          copy=copy, indicator=indicator,
---> 61                          validate=validate)
     62     return op.get_result()
     63 

~/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/merge.py in __init__(self, left, right, how, on, left_on, right_on, axis, left_index, right_index, sort, suffixes, copy, indicator, validate)
    525         if not isinstance(right, DataFrame):
    526             raise ValueError('can not merge DataFrame with instance of '
--> 527                              'type {right}'.format(right=type(right)))
    528 
    529         if not is_bool(left_index):

ValueError: can not merge DataFrame with instance of type <class 'pandas.core.series.Series'>
```

**Comment by tmichela** [comment]
Thanks @fangohr . Is the requirement.txt only required for binder? That's weird because binder should be able to build using setup.py.
I'll have a look if I can improve that (in an other branch)

**Comment by tmichela** [comment]
offline LGTM from @fangohr

**Pull request merged**
